@extends('layouts.public')
@section('title', 'About us')
@section('content')
<section class="page-hero section-shell"><span class="kicker">About Digito Move</span><h1>Moving good ideas from <em>possible</em> to practical.</h1><p>We are a Kampala-based digital product company building technology that helps organisations work better and people move forward.</p></section>
<section class="section-shell narrative-grid"><div><span class="kicker">Our story</span><h2>Built from resilience, curiosity, and a bias toward action.</h2></div><div><p>Digito Move began in May 2021 as an independent software development practice. What started with focused contracts has grown into a multidisciplinary company delivering websites, mobile apps, management systems, and technology support.</p><p>We believe useful technology should be clear, accessible, and grounded in the realities of the people using it.</p></div></section>
<section class="section-shell mission-grid"><article><span class="kicker">Mission</span><h2>Affordable, reliable technology and knowledge.</h2><p>To improve efficiency and productivity for individuals and businesses through dependable software systems and practical digital knowledge.</p></article><article><span class="kicker">Vision</span><h2>Accelerate useful digital migration.</h2><p>To become a leading digital migration solution provider through software, digital literacy, and technology made accessible.</p></article><img src="{{ asset('assets/img/objectives/embracing-tech.jpg') }}" alt="Embracing technology"></section>
<section class="section-shell value-grid">@foreach([['Efficiency','Solutions should make work materially easier.'],['Reliability','Products and partnerships must remain dependable.'],['Technical know-how','Strong delivery comes from practical expertise.'],['Resilience','We keep finding workable paths through constraints.'],['Diligence','The details of implementation matter.'],['Affordability','Useful technology should reach more people.']] as [$title,$copy])<article><span class="kicker">Core value</span><h3>{{ $title }}</h3><p>{{ $copy }}</p></article>@endforeach</section>
<section class="section-shell location-panel"><div><span class="kicker">Our location</span><h2>{{ config('variables.location') }}</h2><p>Meet with us about a project, training, or technology support.</p><a href="{{ route('contact') }}" class="button primary">Contact us</a></div><iframe src="{{ config('variables.mapEmbedUrl') }}" width="100%" height="420" style="border:0" allowfullscreen loading="lazy" referrerpolicy="no-referrer-when-downgrade" title="Digito Move location"></iframe></section>
@endsection
